import type { Product } from "~~/types/products";

export const product: Product[] = [
  {
    id: 1,
    name: "Afang Soup",
    price: 2500,
    desc: "A rich, traditional soup made with okazi and water leaves, often served with fufu.",
    image: "afang.webp",
    alt: "Afang Soup Image",
    category: "food",
    createdAt: "2025-08-06T12:00:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 2,
    name: "Egusi Soup",
    price: 2700,
    desc: "Savory melon seed soup thickened with ground egusi seeds, and often cooked with assorted meat.",
    image: "egusi.webp",
    alt: "Egusi Soup Image",
    category: "food",
    createdAt: "2025-08-06T12:01:00.000Z",
    recomended: false,
    popularity: 0,
  },
  {
    id: 3,
    name: "French Fries",
    price: 1500,
    desc: "Crispy and golden French fries, lightly salted and served hot.",
    image: "french-rice.webp",
    alt: "French Fries Image",
    category: "food",
    createdAt: "2025-08-06T12:02:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 4,
    name: "Fried Rice",
    price: 2000,
    desc: "Flavorful Nigerian fried rice mixed with vegetables and chicken liver.",
    image: "fried-rice.webp",
    alt: "Fried Rice Image",
    category: "food",
    createdAt: "2025-08-06T12:03:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 5,
    name: "Jollof Rice",
    price: 1800,
    desc: "Classic West African jollof rice cooked in spicy tomato sauce.",
    image: "jollof.webp",
    alt: "Jollof Rice Image",
    category: "food",
    createdAt: "2025-08-06T12:04:00.000Z",
    recomended: false,
    popularity: 0,
  },
  {
    id: 6,
    name: "Kpommo Pepper Sauce",
    price: 1200,
    desc: "Deliciously spiced cow skin served in pepper sauce.",
    image: "kpommo-sauce.webp",
    alt: "Kpommo Pepper Sauce Image",
    category: "food",
    createdAt: "2025-08-06T12:05:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 7,
    name: "Nkwobi",
    price: 3000,
    desc: "Traditional Igbo delicacy made with cow foot, richly seasoned and garnished.",
    image: "nkwobi.webp",
    alt: "Nkwobi Image",
    category: "food",
    createdAt: "2025-08-06T12:06:00.000Z",
    recomended: false,
    popularity: 0,
  },
  {
    id: 8,
    name: "Okpa",
    price: 800,
    desc: "Steamed Bambara nut flour snack native to Enugu, soft and filling.",
    image: "okpa.webp",
    alt: "Okpa Image",
    category: "food",
    createdAt: "2025-08-06T12:07:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 9,
    name: "Pasta Delight",
    price: 2200,
    desc: "Creamy pasta served with veggies and a sprinkle of cheese.",
    image: "pasta.webp",
    alt: "Pasta Delight Image",
    category: "food",
    createdAt: "2025-08-06T12:08:00.000Z",
    recomended: false,
    popularity: 0,
  },
  {
    id: 10,
    name: "Shawarma Roll",
    price: 1800,
    desc: "Tasty meat-filled shawarma wrapped with vegetables and sauce.",
    image: "shawama.webp",
    alt: "Shawarma Roll Image",
    category: "food",
    createdAt: "2025-08-06T12:09:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 11,
    name: "Lime Juice",
    price: 1000,
    desc: "Refreshing and tangy lime juice served chilled.",
    image: "lime.webp",
    alt: "Lime Juice Image",
    category: "drinks",
    createdAt: "2025-08-06T12:10:00.000Z",
    recomended: false,
    popularity: 0,
  },
  {
    id: 12,
    name: "Watermelon Juice",
    price: 1000,
    desc: "Cool and hydrating watermelon juice perfect for sunny days.",
    image: "strawberry.webp",
    alt: "Watermelon Juice Image",
    category: "drinks",
    createdAt: "2025-08-06T12:11:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 13,
    name: "Orange Juice",
    price: 1000,
    desc: "Freshly squeezed orange juice packed with vitamin C.",
    image: "orange.webp",
    alt: "Orange Juice Image",
    category: "drinks",
    createdAt: "2025-08-06T12:12:00.000Z",
    recomended: false,
    popularity: 0,
  },
  {
    id: 14,
    name: "Strawberry Juice",
    price: 1200,
    desc: "Sweet and flavorful strawberry juice with a vibrant taste.",
    image: "strawberry.webp",
    alt: "Strawberry Juice Image",
    category: "drinks",
    createdAt: "2025-08-06T12:13:00.000Z",
    recomended: true,
    popularity: 0,
  },
  {
    id: 15,
    name: "Pineapple Juice",
    price: 1100,
    desc: "Tropical pineapple juice that’s sweet, tangy, and energizing.",
    image: "pinapple.webp",
    alt: "Pineapple Juice Image",
    category: "drinks",
    createdAt: "2025-08-06T12:14:00.000Z",
    recomended: true,
    popularity: 0,
  },
];
