import type { Product } from "~~/types/products";

export const products: Product[] = [
  {
    id: "1",
    name: "Afang Soup",
    price: 2500,
    desc: "A rich, traditional soup made with okazi and water leaves, often served with fufu.",
    image: "afang.png",
    category: "food",
  },
  {
    id: "2",
    name: "Egusi Soup",
    price: 2700,
    desc: "Savory melon seed soup thickened with ground egusi seeds, and often cooked with assorted meat.",
    image: "egusi.png",
    category: "food",
  },
  {
    id: "3",
    name: "French Fries",
    price: 1500,
    desc: "Crispy and golden French fries, lightly salted and served hot.",
    image: "french-fries.png",
    category: "food",
  },
  {
    id: "4",
    name: "Fried Rice",
    price: 2000,
    desc: "Flavorful Nigerian fried rice mixed with vegetables and chicken liver.",
    image: "fried-rice.png",
    category: "food",
  },
  {
    id: "5",
    name: "Jollof Rice",
    price: 1800,
    desc: "Classic West African jollof rice cooked in spicy tomato sauce.",
    image: "jollof.png",
    category: "food",
  },
  {
    id: "6",
    name: "Kpommo Pepper Sauce",
    price: 1200,
    desc: "Deliciously spiced cow skin served in pepper sauce.",
    image: "kpomo.png",
    category: "food",
  },
  {
    id: "7",
    name: "Nkwobi",
    price: 3000,
    desc: "Traditional Igbo delicacy made with cow foot, richly seasoned and garnished.",
    image: "nkwobi.png",
    category: "food",
  },
  {
    id: "8",
    name: "Okpa",
    price: 800,
    desc: "Steamed Bambara nut flour snack native to Enugu, soft and filling.",
    image: "okpa.png",
    category: "food",
  },
  {
    id: "9",
    name: "Pasta Delight",
    price: 2200,
    desc: "Creamy pasta served with veggies and a sprinkle of cheese.",
    image: "pasta.png",
    category: "food",
  },
  {
    id: "10",
    name: "Shawarma Roll",
    price: 1800,
    desc: "Tasty meat-filled shawarma wrapped with vegetables and sauce.",
    image: "sharwama.png",
    category: "food",
  },
  {
    id: "11",
    name: "Lime Juice",
    price: 1000,
    desc: "Refreshing and tangy lime juice served chilled.",
    image: "limme.png",
    category: "drinks",
  },
  {
    id: "12",
    name: "Watermelon Juice",
    price: 1000,
    desc: "Cool and hydrating watermelon juice perfect for sunny days.",
    image: "water-melon.png",
    category: "drinks",
  },
  {
    id: "13",
    name: "Orange Juice",
    price: 1000,
    desc: "Freshly squeezed orange juice packed with vitamin C.",
    image: "orange.png",
    category: "drinks",
  },
  {
    id: "14",
    name: "Strawberry Juice",
    price: 1200,
    desc: "Sweet and flavorful strawberry juice with a vibrant taste.",
    image: "strawberry.png",
    category: "drinks",
  },
  {
    id: "15",
    name: "Pineapple Juice",
    price: 1100,
    desc: "Tropical pineapple juice that’s sweet, tangy, and energizing.",
    image: "juice-5.png",
    category: "drinks",
  },
];
